#
#   This .bashrc part is for the Elrond Nodes Commands 
#

# ----------- Launch the Monitoring of the first Node

alias node-monitoring="./elrond-utils/termui --address localhost:8080"

# ----------- Start & Stop the Node(s) present on the machine

alias node-start="./elrond-go-scripts-testnet/script.sh start"
alias node-stop="./elrond-go-scripts-testnet/script.sh stop"

#------------------------------------------------------------